kiwix/kiwix-js

www/js/lib/zimArchive.js

Fixed a bug about titles not being found because ZIM sorts empty titles to the end (this includes all auxiliary files like images).
Furthermore, added the check whether the search prefix is actually a prefix of the title.
Fixes #122
Fixes #104

Zim title search

---

tests/tests.js
www/js/lib/xzdec_wrapper.js
www/js/lib/zimfile.js

The problem was that in some cases, the input was already read in too
far, so we just re-start the decompressor for each read (the full
contents of a file are read in one go anyway).

Fix streaming bug in xz decompressor.

---

www/js/app.js

Make CSS dependencies work on Firefox OS devices.

---

service-worker.js
www/js/app.js

It's necessary for some of them that have special characters in it.
For example the main image of article "Modern Sounds in Country and Western Music" in the Ray Charles ZIM file : the filename has a & in it, which was encoded as %26. We need to decode it as & before passing it to the backend.

Decode URI encoding for dependencies (images, JS, CSS etc).

---

www/js/lib/zimArchive.js

And not other types of contents (javascript etc).
Fixes #151 
plus a small fix in title search, for the case where an article title is exactly the prefix

Modify the ZIM backend, so that findTitlesWithPrefix only returns articles

---

www/js/app.js

When randomly selecting a title, we could end up on a content with any namespace
For example images, javascript, CSS etc.
Now, if this happens, we randomly select another title, until we find a content
with namespace 'A' (i.e an article).
Fixes #141

The random article feature must not display titles with a namespace!=A

---

www/js/lib/zimArchive.js

The redirection algorithm was considering the redirectTarget as a TitleIndex
instead of a UrlIndex.
That was sometimes causing some infinite loops, and often opened the wrong
article when clicking on a link.
Fixes #106
Fixes #133

Fix in the redirection algorithm, that was leading to the wrong article.

---

README.md
www/index.html

The main target is now browser extensions, not Firefox OS
(even if it's still compatible with).
Fixes #208

Update README and About section to reflect the new target of this app.

---

.travis.yml
manifest.json
manifest.webapp
scripts/create_all_packages.sh
scripts/package_listed_firefox_extension.sh
www/index.html

The firefox extension id is kiwix-html5-unlisted by default.
The new package_listed_firefox_extension.sh allows to change this id
and upload a package ready to be submitted to Mozilla.
Fixes #213

Make Travis package/deploy only on cron, and change Firefox id.

---

README.md
manifest.json
manifest.webapp
www/index.html
www/js/app.js

There must be an uppercase as the first letter.
Fixes #225

Change case of wikipedia and wikimedia words in UI and README.

---

tests/tests.js
www/js/app.js
www/js/lib/zimDirEntry.js

"article URL" should have been used instead of "article Title" when saving browser history state. But when these terms are being read from the DirEntry "article Namespace" is being prepended to url and stored as url. The fix is to stop doing this prepending. That keeps it consistent to the reader when "DirEntry.url" is reqd and when "DirEntry.namespace + '/' + DirEntry.url" is required. Further details [here](https://github.com/kiwix/kiwix-html5/issues/177#issuecomment-296538463)
Changes:
www/js/zimDirEntry.js
url should not hold namespace + url
www/js/app.js
In gotoRandom, handleTitleClick, gotoMainArticle
now passes title.url instead of title.name() to pushBrowserHistoryState
www/js/app.js, tests/tests.js
Replaced occurances of title.url with title.namespace + title.url

Fixes #177 History Navigation

---

www/css/app.css

"Random" button displays over Wiki page in Windows 10 Mobile portrait orientation. Fixes #250 . However, if we upgrade bootstrap to version 4.0, check if this fix is still needed.

Fixes #250 Random button display bug

---

README.md
nbproject/project.properties
nbproject/project.xml
tests.html
www/index.html

Rebrand candidate files

---

nightwatch.js

To workaround some random timeouts in Travis on Firefox>=48
Fixes #251

Use version 47 of Firefox in nightwatch unit and UI tests.

---

scripts/package_ubuntu_touch_app.sh

Else the package is rejected by click-review

Fix double-quotes handling to actually remove *.woff* from click package

---

www/index.html

[ Kiwix-JS #302 ]
Apart from panels, I have included a skeleton Bootstrap grid layout (responsive divs with flexbox) on the page. These can be arranged as desired by adding classes described at https://getbootstrap.com/docs/3.3/css/#grid-options . More advanced options will only make sense if we introduce more options / panels and a non-expert settings section.

Use Bootstrap panels to organize Configuration page #302

---

.travis.yml
browser-tests/nightwatch_runner.js
nightwatch.js

Instead of only one version of Firefox, this PR makes the automated unit and UI tests run on : 
- Firefox 45
- latest version of Firefox
- latest version of Chrome
- latest version of Edge
- Internet Explorer 11 (skipping the unit tests because they don't work, but the UI tests do work)

Use several browsers for automated unit and UI tests

---

www/js/app.js

Fixes #329
It was affecting all <img> tags of the first displayed article, only
in ServiceWorker mode.

Fix a regression on some images in ServiceWorker mode.

---

www/dummyArticle.html
www/index.html
www/js/app.js

24th Feb: The latest commit ([Inject baseUrl](https://github.com/kiwix/kiwix-js/pull/342/commits/3b5f7b28ae323e1c4f2e0002433c89846279a770)) incorporates #343 (Add the <base> tag before the document is injected into the DOM). It has been tested on Microsoft Edge, Internet Explorer, Firefox and FFOS simulator.

Void the iframe in readArticle function #341

---

service-worker.js
www/js/app.js

It is necessary to let the browser know in which directory it is.
Else the relative links can be broken if the original URL is in a
different directory than the final URL.
Fixes #312

Send an HTTP Redirect in SW mode when there is a ZIM redirect.

---

tests/tests.js
www/js/app.js
www/js/lib/zimArchive.js

See discussion in #370 . It has yet to be determined whether JavaScript files should also be decoded as UTF8, or, since we will store them as Blobs, whether a binary format is appropriate for the browser to decode. Since we do not yet use the JavaScript function, that should be left to future investigation.

Read CSS as utf8 strings instead of binary

---

www/js/app.js

Instead of calling displayArticleInForm like in jQuery mode.
I also removed some tests on jQuery/ServiceWorker modes in displayArticleInForm, as this function is now only used in jQuery mode.
And I renamed it to displayArticleContentInIframe
Fixes #382

In ServiceWorker mode, set the iframe src to display articles.

---

www/index.html
www/js/app.js

@mossroy , I agree that this is a less risky way of solving (or rather, ameliorating) #381 for a v2.3 release.
I've implemented your helpful suggestions in commit https://github.com/kiwix/kiwix-js/commit/127ff299de66c16398e250dc56fbd696a0388ee8. Tested on IE, Edge, FFOS, Firefox Quantum.
I've also, optionally, added a commit https://github.com/kiwix/kiwix-js/commit/41f1b7042ac87ba83e171e0a42416a836f67bd42 which displays an additional message to the user when the app is retrieving CSS from the ZIM instead of the cache. Because that is slow, and because first impressions often count strongly with apps, giving this additional small piece of feedback could be a user-friendly gesture. The message won't display again on subsequent page loads unless a further piece of CSS needs to be cached. …

Prevent render until all CSS is fulfilled

---

service-worker.js
www/js/app.js

This proposes a pragmatic solution to #390. For ServiceWorker, I have merely added SVGs to the pragmatic code that is already there (that type was missing).
For jQuery, I've used a more compact solution. These regexes are extremely small and quick for the system to match, and I'm not sure anything much would be saved by compiling them in advance, given that the bottleneck is extraction from the ZIM. Speedup here is probably immaterial and the operations can easily be completed in a minute fraction of the time between images arriving. EDIT: ah, of course I forget, unless we're using a Worker, there is no "time between", as there is only one thread. But it's still probably minimal.
In any case, this is probably "meanwhile" code, unless someone would like to bite the bullet with #137 now?

Add more specific mimetype support for images #390

---

www/js/app.js

Instead of waiting for the "load" event.
On big articles, it allows some browsers to display the content even if it is not fully loaded (missing images etc).
It can make a big difference in the user perception of performance.
Fixes #413

Display the content immediately after a search in ServiceWorker mode.

---

www/js/app.js

Fixes #416 
It seems to do the job, but I don't measure any performance difference on big wikipedia articles (which I hoped it would speed-up).
Maybe it would be worth on bigger resources like videos? (but we don't support them for now)
I managed to check that the buffers are transferred by adding lines like below before and after the transfer : 
`console.log("length of content.buffer=" + content.buffer.byteLength);`
The length drops to zero after the postMessage.

Transfer the data from ZIM to ServiceWorker instead of copying it.

---

www/js/app.js

Fix broken ServiceWorker when switching between modes.

---

www/js/app.js

Automatically fallback to jQuery mode if the SW fails to register.

---

www/css/app.css
www/index.html
www/js/app.js

@mossroy I've taken the CSS spinner code as far as I can without hooking into the Service Worker messaging channel. So it works fully in jQuery mode, and in a limited way in Service Worker mode: when loading a new page by searching for it, with the Random button, or when loading the landing page, but not when clicking on a link within a page. The latter would require hooking into the messaging channel, and so would require a policy decision if we want uniformity across the app. It can be left for future decision.
Regarding your comment in #425 that keeping the old page on-screen until we have the new html to replace it might cause the app to keep requesting images unnecessarily, I have done extensive testing in #426 : there is a broader issue affecting master, not this PR specifically, so …

Add a modern CSS spinner

---

tests/tests.js
www/js/lib/zimArchive.js

Fixes #395
It is especially useful to read the language of the ZIM file

Add API for reading ZIM Metadata.

---

www/js/app.js

This problem is a bit tricky. In essence, the malformed href causes a crash on any attempt to access any property of the href. This means we have two choices: use jQuery, with its in-built error handling, or else we have to use try … catch. So I'm posting two commits here, one with jQuery and the second with try … catch. Both solve the issue. @mossroy , if you prefer the jQuery solution, or a variant of it, I'll revert the second commit. Although generally I prefer not to use jQuery when it's unnecessary, here I think it provides a tangible benefit, so I'm inclined towards the jQuery solution.

Prevent app crash with malformed hrefs

---

scripts/create_all_packages.sh
scripts/package_firefox_extension.sh

We have move `download.kiwix.org` server to a new server. A few things have changes:
* the CI user is now `ci` instead of `nightlybot`
* the path is now `/data/download/` instead of `/var/www/download.kiwix.org/`
Here is a patch to get Kiwix JS nightlies uploaded again (this has stopped to work during this week).

Update CI to deal with new download.kiwix.org server

---

www/js/app.js

The evolution of this code is tracked in #172 . I believe the issues I identified there have been solved.
The code is generalized to work with `<video>` and `<audio>` blocks, together with any `<source>` tags contained within them. Hence I call it "media playback" rather than just "video". I have tested with video and audio provided in different ZIMs, but note that I did not find any ZIM using pure `audio` blocks -- the scrapers seem to put any audio in video blocks (and it plays fine like that). Details of some pages to test with in #172.
Playback works in browsers without needing JavaScript-in-the-ZIM to be enabled, although sometimes getting to the content is a little challenging without JS (but basically our standard search usually works). I have tested the code with FFOS (works in …

Enable media playback in JQuery mode

---

www/js/app.js

This PR fixes #449 . It also shortens `regexpTagsWithZimUrl` by using a non-capturing lookahead, and does not depend on matching the full URL, only the path (which is all we're interested in). See #449 for discussion. So far, I've tested with Edge and Firefox ESR, on Wikimedia, TEDx and stackexchange ZIMs. Testing against unescaped apostrophe was done with the article `Giudicato_of_Logudoro.html` in full English Wikipedia.

Support unescaped characters in asset URLs

---

www/js/app.js

This PR is an alternative to #447 . It fixes #446 with regard to text tracks only, because I believe that subtitles are the only assets that can be in the A namespace, and hence the only ones that could have a URL relative to the article.
~~However, as a result of #447, I discovered that the regex (see code at beginning of PR changes) could be written in a way that reduces some backtracking, so I've included that optimization from the other PR. According to RegexBuddy's debug tab, writing the regex this way shaves off some 900 steps in a typical search through an article of 11,000 steps. That is about 8% faster. We're talking 8% of milliseconds, so it's minor, but worth including, I think.~~

Support relative text tracks in the A namespace

---

www/css/app.css
www/index.html
www/js/app.js
www/js/lib/uiUtil.js

This is a first go at addressing #466. I have backported the UI features and detection of the active content warning from Kiwix JS Windows. It intelligently detects an unsupported UI and puts a yellow Bootstrap `alert-warning` just below the search box. The alert is only shown on the landing page (otherwise it would become very annoying), and is removed when the user presses Config or searches for articles. By default, it will appear again whenever the user goes back to a landing page with active content.
The alert can be dismissed temporarily (with the x) or permanently. Hyperlinks to the appropriate settings on the Config page are provided (to activate SW mode, and to hide the warning permanently), and these hyperlinks jump to (and highlight) the setting the user needs to activate. The …

Add active content warning in jQuery mode

---

www/index.html
www/js/app.js
www/js/lib/uiUtil.js

This code addresses issue #439 . Currently the epub links in Guttenberg ZIMs are useless in jQuery mode. This PR handles the "download" of the epub from the ZIM to the OS's filesystem, or to open the file using the browser's open method. The code is tested and working with `gutenberg_es_all_2018-10.zim` in Edge, Chromium 66, Firefox ESR, FFOS simulator, and IE11.
Since JS doesn't work, to choose a book to test, type a space in the search field, and choose any title with the word "(cover)" in the name. Then click on the big red download icon (not the HTML5 icon, which is a simple html/text-based version of the book). In some browsers the file will automatically be saved in the download location set in the browser. In others, the user is offered a choice to save the file or open it.
The …

Support epub and other downloads from ZIM in jQuery mode

---

www/js/app.js

This is an initial attempt to address #479 . There is only one other place that `goToArticle` is called, and it is `window.onpopstate`. Quick testing of this code in one browser (Edge) so far seems to suggest that this solves the problem, but we may need to add a `removeURLParameters` in the `onpopstate` function as well.

Enable extraction of filenames with question marks

---

www/js/app.js

This is a very simple PR that merely hides the navigation buttons in the footer when the user clicks the About or Config buttons, and shows them again when the user clicks Home. It addresses a small part of #337 , but also shows how easy it is to hide the bottom bar for users who don't want it.

Hide navigationButtons when in Config or About

---

www/js/app.js

This PR addresses #484. It turned out to be very easy.
Because I needed to use `e.preventDefault` (as per https://stackoverflow.com/questions/29921696/can-i-have-an-onclick-event-on-a-imagemap-area-element), it seemed best to change jQuery calls to pure JS in the `parseAnchorsJQuery` function, so as not to confuse styles. This function is now fully consistent with `insertMediaBlobsJQuery`, which also uses pure JS. Removal of jQuery makes it appear that there are more changes than there actually are, but on examination, it will be seen that they are merely stylistic changes.
Area maps and normal links are tested and working in this PR with `wikivoyage_en_all_novid_2019-03.zim` in Edge 44, Edge 75 (Chromium), IE11, Firefox ESR. I have also tested a Stackexchange ZIM to be sure that the use …

Add support for area tag

---

www/index.html
www/js/app.js

This is a (relatively) easy PR addressing an old issue #29.
The entire app is enabled as a drop target, so a file can be dropped anywhere except in the populated iframe. I experimented with trying to enable dropping onto the iframe, but it would have required injecting scripts into the frame, which seems excessive, since the file can easily be dropped anywhere above it. 
Once a file has been selected in this way, the file picker and instructions are hidden, but a link is provided to show them again if the user wants to use the file picker.

Enable drag and drop of ZIM files

---

tests/tests.js
www/js/app.js
www/js/lib/zimArchive.js
www/js/lib/zimDirEntry.js
www/js/lib/zimfile.js

~~This PR is *not* ready to merge. I'm opening it in order to test the prototype code and get help on it.~~
The code is in a working state (in jQuery mode so far), but has a problem I'd like help with. It reads the mimeTypeList correctly and stores it in a prototype Map. This works well, and prevents reading the binary data from the ZIM file multiple times per page load. Pages load successfully, and assets are assigned the correct MIME type.
~~The problem is that the map unexpectedly persists between ZIM file loads, which is not good. I don't know how to place it in the ZIM file scope. I shouldn't have to erase it explicitly on new archive load, because it's a prototype of  ZIMFile -- see zimfile.js line 114:~~
~~`ZIMFile.prototype.mimeTypeMapCache = new Map;`.~~
~~I'm fairly new to …

Read mime type list from zim archive

---

.travis.yml
browser-tests/nightwatch_runner.js
nightwatch.js
www/js/app.js

This fixes #39 and the regression in #442.
The behaviour is as follows:
* User can dismiss search results with Esc, click/tap anywhere outside of prefix (search box), or with tab;
* Search results are not lost, they are hidden;
* If user re-enters prefix (if it gains focus), then the search results are shown again if prefix is not empty.
In the process, testing on FFOS where the on-screen-keyboard causes drastic screen resizes, I discovered an obsolete value still being used, erroneously in the `resizeIframe()` function. Since we now float `articleListWithHeader` over the article, we shouldn't subtract its height from the `window.outerHeigh`. It causes a drastically shortened screen otherwise.
I have coded this with jQuery for the sake of consistency with surrounding code.
Tested in Edge …

Hide article list on prefix blur or on Esc

---

www/css/app.css
www/js/app.js
www/js/lib/uiUtil.js

This addresses #55 . It also has the functionality of #499 built into this PR, but #499 could be merged first in order to keep the development steps in order. This is tested on Edge 44, Edge 76, Firefox ESR, Internet Explorer 11. It also works on FFOS simulator if using the computer keyboard to select titles. However, this isn't really relevant in that context, I think.
There is one display bug on FFOS simulator only, which is that if we scroll down (with down arrow on computer keyboard) a long list of found titles, and then scroll back up (with up arrow), then the whole app scrolls up a little in the IDE, leaving an odd space at the bottom. I think this is just an artefact of the simulator, and I guess it can't be tested on a real device because a keyboard can't be attached.
The other …

Allow keyboard selection in search list

---

service-worker.js
www/js/app.js
www/js/lib/uiUtil.js

This is a PR to apply the use of `dirEntry.getMimetype()` throughout the code as per #500.
So far I have done Service Worker. I need to check if there are other places remaining where we could use this function.

Apply dirEntry.getMimetype throughout code

---

service-worker.js
www/js/app.js

So that the browser cache does not mix content between different ZIM files.
Fixes #530 (as long as only relative URLs are used).
@kelson42 : in #138, you told me that the ZIM files should only use relative URLs (since the end of 2014). Can we rely on that?
Because, if ZIM files use absolute URLs in some hyperlinks, the prefix disappears and there might still be some cache issues.
I suspect that it still happens on some recent ZIM files

Add the ZIM file name as a prefix of the iframe URL, in SW mode.

---

www/js/app.js

This is a simple PR that fixes #494 in SW mode while still allowing #428 to work.
At first I thought the solution was to use `encodeURI` instead of `encodeURIComponent` as per https://stackoverflow.com/a/12650216/9727685. However, it turns out that `encodeURI`, while not encoding the forward slashes, also doesn't encode `$` and other special characters that need to be encoded in order for #428 to work. So, I have to apply `encodeURIComponent` only to text between the slashes, which is what this PR does.
Tested on Wikipedia's `Presidential $1 Coin` article, and also tested on Stackexchange ZIMs as discussed in #494. So far, only tested on Edge.

Deal correctly with forward slashes in article URL in SW mode

---

www/index.html

Have moved all the links to HTTPS and tested if they still work.
I have also removed a link regarding Evopedia archive because (1) the link to the format description seemed dead (2) I'm not sure this is well tested (3) I'm not sur this is still so pertinent. That said not problem to reintroduce that link (with no dead link).

Move HTTP links to HTTPS

---

tests/tests.js
www/js/lib/util.js

Remove unused removeDuplicateTitlesInDirEntryArray() #491

---

service-worker.js
www/index.html
www/js/app.js

This addresses ~~#441~~ #414. It adds the native Cache API to `service-worker.js` for the caching of css and js assets. It significantly speeds up SW mode. The cached entries can be checked in the Cache entry of devtools in Chromium or Edge (I didin't try with Firefox). Example of running this on the most recent Ray Charles is shown in the image below (from Chromium / Edge 78). This is not for merging yet, but I would appreciate testing and any comments.
I think the main TODO is to provide a mechanism for deleting / pruning entries. We could just do it on change of ZIM, but as the quota on most devices is quite generous, and as the entries are unique to each ZIM, a more subtle mechanism could be found. We could provide usage statistics on the Configuration page and a button to clear the …

Add native asset caching to Service Worker

---

www/index.html

This addresses #548. Let me know what you think of the suggested text. As mentioned in the issue, the CSP should prevent most cases of scripts accessing external files, but we don't know all the contexts in which this app could run, and in some contexts it is definitely possible for scripts to access external servers (especially if the external server serves permissive CORS headers). So I believe the warning here is appropriate now that we execute scripts from ZIMs in SW mode.

Update Privacy Policy

---

www/css/app.css
www/css/kiwixJS_invert.css
www/css/kiwixJS_mwInvert.css
www/index.html
www/js/app.js
www/js/init.js
www/js/lib/uiUtil.js

This backports (but with much improved and generic coding) a dark theme as described in #265.
I have implemented this as a generic theming system, though only three themes are currently implemented: `light` (the current default); `dark` (a theme for the app shell only); and `dark_invert` (a theme for the app shell and the content in the iframe). The screenshots below shows the `dark_invert` theme.
The app shell themes do not touch the document loaded in the iframe. the content theme of course has to attach a stylesheet, using DOM methods, after the document has loaded. It works in both jQuey and Service Worker modes.
Inversion is carried out by adding a simple inversion filter to the iframe element (`articleContent`), but we have to attach a stylesheet to the iframe document to re-invert …

Implement a theming system (dark theme / night mode)

---

www/js/app.js
www/js/lib/q.js
www/js/lib/util.js
www/js/lib/xzdec_wrapper.js
www/js/lib/zimArchive.js
www/js/lib/zimfile.js

Implements #588 for almost all of the deprecated methods and patterns. I have not touched the patterns in `abstractFilesystemAccess.js` because they are FFOS-specific, and I guess this code will not be transferred to any ES6-webkit-npm version. I have kept Q, however, for backwards compatibility with old devices. To dispense with Q, we would simply need to change `Q.Promise()` patterns to `new Promise()`.
I have standardized on using Q with a capital letter (we have some variation).
There is one case of a `Q.when` which is not in the Promise spec. I haven't touched it (yet?) because I don't know what the difference is between when and then in Q.

Update Q and deprecated Promise patterns and methods

---

www/js/lib/zimfile.js

This PR is a fix for #628 and #629 (partially) and #621 . It restores the ability of the app to read the MIME type list in newer ZIMs which have relocated the urlPtrPos to the end of the archive. The same solution has been adopted in libZim - see https://github.com/openzim/libzim/issues/353. The solution is to limit the maximum size of the slice being searched for the MIME type list to 1024 bytes. If the ZIM reports it as being less than that, then the lower value is accepted.

Do not assume urlPtrPos is just after mimeList when reading it

---

www/js/lib/settingsStore.js

Fixes #627 . I used strict as I couldn't find any reason or code to use Lax. The cookie is set only for this and doesn't need to set to any other value.

Updated cookie to ensure samesite is set as Strict.

---

CHANGELOG.md

This contains (in anticipation) one unmerged change (#617).
I have also added a blank line between the title of each release and the list of changes, since the markdown spec requires this according to [this markdown lint rule](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md#md022).

Update CHANGELOG for v2.8.0

---

PRIVACY_POLICY.md

I need a publicly accessible Privacy Policy to publish our app in Edge Add-on Store, so I'm making it available on this branch, so I can reference it. But I think we could add it to master easily. It's just a copy of our current policy embedded in the app.

Make Privacy Policy publicly accessible

---

www/js/lib/filecache.js
www/js/lib/util.js
www/js/lib/zimfile.js

As discussed in #595, this PR implements #619 and revives #183. It is almost entirely @peter-x's code. I have simply tuned the cache size based on my experience running this in KJSW, and have added a faster method of reading an arrayBuffer from the updated Blob API that elminates the need to use FileReader (for those browsers that support the new method).
Apart from Edge (Chromium), I have tested very quickly on Firefox OS simulator (working) and on IE11 (working).
I have left in a console log output that shows the block cache hits and misses, as well as the percentage hit rate. Below is from IE11 console log when running the full 96GB English Wikipedia and searching for "the second world war". You can clearly see here the number of file reads that are avoided and an impressive 100% hit …

Add a low level block cache

---

www/js/app.js

Fixes #667 for latest WikiMed ZIMs. The warning is triggered because a new inline script block has been added to the landing page that looks like this:
`<script>let articleId = 'Wikipedia:WikiProject_Medicine/Open_Textbook_of_Medicine2'</script>`
The fix is to add another exemption to our `regexpActiveContent`. The full amended regex is:
`var regexpActiveContent = /<script\b(?:(?![^>]+src\b)|(?=[^>]+src\b=["'][^"']+?app\.js))(?!>[^<]+(?:importScript\(\)|toggleOpenSection|articleId\s?=\s?['"]))(?![^>]+type\s*=\s*["'](?:math\/|[^"']*?math))/i;`
And the added code is: `|articleId\s?=\s?['"]`. This expands the negative lookahead so that any inline script that contains `articleId = '` will **not** match, and so will not trigger the Active Content Warning. I have made it as generic as possible …

Exempt articleId assignment from Active Content Warning

---

tests.html

Follows-up 0c530101573cf95b, which removed this from www/index.html, but it was still present in the test suite.
This is now loaded automatically by RequireJS.
-------
/cc @Jaifroid per https://github.com/kiwix/kiwix-js/pull/672/files/20229d190570f25a1bbed0353881579a394be221#r528327775
-------
This supersedes the fork-PR at https://github.com/kiwix/kiwix-js/pull/675.

tests: Remove redundant xzdec.js include

---

www/js/app.js
www/js/lib/uiUtil.js

This implements #671 and #505 in jQuery mode. I have removed the WebP image queue from `uiUtil.js` and have transferred the same self-invoking recursive function to the `loadImagesJQuery()` function in `app.js`.
This greatly improves UX on long articles with lots of images, since it ensures that images are loaded from the top of the page, sequentially. The images extracted first are those in the visible area ("above the fold").
Additionally, this PR partially implements #426 for jQuery mode image assets, cancelling extraciton of images if a user navigates away from the page. This is a side-effect of a need to avoid an error if the `images` array is not redefined cleanly. Cancellation does not occur at a very low level, but is still relatively effective (tested with a console log, removed …

Extract images sequentially in jQuery mode

---

.github/workflows/CI.yml
tests/karma.conf.local.js

Follows-up 55186c8. I had this check originally, but then removed it after GitHub merged the upstream improvement.
It looks like some CI runners might not yet have it applied, so keep it a little longer for now.

tests: Use Chrome for 'npm test' in GitHub CI

---

service-worker.js
www/js/app.js
www/js/lib/uiUtil.js
www/js/lib/zimArchive.js
www/js/lib/zimfile.js

This is preliminary work on #597.
I've done some hacks to the code in jQuery mode (for now) as a proof-of-concept.
This supports reading and showing articles in the sample ZIM file `wikipedia_en_ray_charles_2018-09_nons.zim`. It is also backwardly compatible with older ZIM files. It supports searching for a title, with the proviso that results are not yet filtered for an article MIME type.
One confusing thing is that the landing article of this ZIM is in namespace '-' instead of 'W' or 'C'. This could simply be an earlier version of the spec.
Service Worker mode is not currently working.

Support ZIM archives with no namespace

---

www/js/lib/zimArchive.js
www/js/lib/zimfile.js

This fixes #720.
It turned out to be an interesting logical problem. For a legacy (i.e. current) ZIM format, the random function takes the full range of titles in the title pointerlist and hops through it until it finds an article. The title pointerlist is merely the entire list of dirEntries ordered by title, as opposed to url. The number of entries in the title pointerlist is thus the same as the number of entries in the url pointerlist, which is equal to the number of directory entries. Random is therefore quite inefficient, because it is trying to find a random article in a sea of other directory entries (e.g. the number of images can easily outnumber the number of articles).
However, in a v1 no-namespace ZIM, we will have an article pointerlist which is the subset of dirEntries that …

Calculate true number of articles in a legacy ZIM

---

www/js/app.js

The no-namespace ZIM `beer_stackexchange_com_2021-07.zim` has exposed a coding error in Kiwix JS. The `classList.add()` method was being used incorrectly to add a list of classes with a simple string separated by a space (e.g. "myClass1 myClass2"). This turns out to cause an exception, and we have been lucky up till now that no ZIMs previously appear to have had multiple classes on the html element. The correct syntax is `classList.add("myClass1", "myClass2"). The [documentation at MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add) is a bit misleading, because it says the method accepts "A DOMString representing the token (**or tokens**) to add to the tokenList" (my bold). In fact the string must contain a single token.
This simple PR corrects this generically, and …

Correct usage of classList method

---

CHANGELOG.md

I think it's best to add the TODO for the next version as part of the step for preparing source code for v3.3.0, and not show it in the tagged version of v3.2.0. However, if you don't agree, I'll happily replace it now.

Update CHANGELOG for v3.2.0

---

CHANGELOG.md
manifest.json
manifest.webapp
scripts/create_all_packages.sh
ubuntu_touch/manifest.json
www/index.html

@mossroy I think this is all the places where we update the version number. This is for merge into master.
As a separate point, I propose that the implementation on GitHub pages should be set to the release tag, rather than to master with the source code. updated to -WIP. If you're happy with that, I can do that.

Update source code to v3.3-WIP

---

www/js/app.js

Fixes #760. Although that should be fixed in the YouTube scraper, it will take a long time for that fix (if it is accepted) to come through to new ZIMs. This patch is a one-liner in the specific jQuery code that inserts media blobs, so I think it is worth doing, as it will redstore the ability to play videos to existing ZIM archives as well.
I tested this on `khan-academy-videos_en_special-relativity-physics-khan-academy_2021-03.zim`.

Add missing controls property to media containers

---

www/js/app.js

This is a hypothetical but realistic bugfix. I realized that the ZIM URI detection in jQuery mode should theoretically exclude some other potential URI types that could be found in some ZIMs. We currently exclude only URIs beginning 'http' (to include 'https') from processing as ZIM URIs -- i.e. URIs that point to external resources. However, this could lead to errors or unnecessary processing with URIs with the protocol 'data:'. These are perfectly conceivable for either CSS or images, so should be excluded explicitly from processing.
I know that Firefox OS doesn't allow data URIs for CSS (I think), but does allow them for images (I think) -- or is it the other way round? But that is rather specific to that OS.
I did wonder also whether we should add 'javascript:' as another protocol …

Tweak regular expression that detects ZIM URIs

---

www/index.html
www/js/app.js

Fixes #782
Added the attribute `draggable=false` to the bottom navigation bar to prevent it from causing unexpected behavior.

Disable dragging of some elements

---

.github/workflows/CI.yml
scripts/Check-OfflineFilesList.ps1

Testing CI solution for #772 .

Check offline files list through CI

---

www/js/app.js

Fixes #795.
The reason the code did not work is that this check is made from the extension, while the Service Worker of the https://moz-extension.kiwix.org implementation is suspended, because that page is not active. Loading an image from a domain appears not to be sufficient to wake up the Service Worker controlling that domain (and for good reason!).
We could possibly wake up the Service Worker so that it can indicate that it is installed if we loaded the app into an iframe. But that seems like real overkill and it would introduce a noticeable delay between launching the app and passing through to SW mode. We would essentially have to load the PWA twice, once in an iframe to confirm that it is available, and again when we pass through. The only gain is in some rare edge cases where the …

Revert check for PWA existence prior to passthrough

---

README.md

This is a follow-on from #771, to provide some cleanup of documentation especially regarding the new implementation.

Update documentation to include new implementation

---

CONTRIBUTING.md
README.md

Added the CONTRIBUTING.md file in the repo and linked it inside the newly created "Contributing" section of the README.md
- Added a "Contributing" section in the README.md file with the link to the newly created CONTRIBUTING.md file and a link to join our Slack workspace
- Created a new CONTRIBUTING.md file with the text by @Jaifroid mentioned in Issue #792 
- Added instruction to carry out extension version testing in the browser(needs review here @Jaifroid ) 
Needs review in the following changes:
- Testing the extension versions locally (line number 21-23 in CONTRIBUTING.md)
- Here, I mentioned just for the chrome, how can we cover other platforms too? Also, should we also link instructions to load an extension's source code in the browser
- Added Slack link in the README.md's …

Added CONTRIBUTING.md : WIP

---

service-worker.js
www/css/app.css
www/index.html
www/js/app.js
www/js/lib/settingsStore.js
www/js/lib/uiUtil.js

This is intended to address #794, because we have a number of new developers who will find the new functionality confusing.
This provides a UI for resetting the app (see screenshot) under Expert Settings.
The button "**Reset**" performs a full app reset consisting of:
* Warning the user and seeking confirmation
* Clearing any cookie entries
* Clearing any Local Storage entries
* Deleting the Cache API caches
* Deregistering any registered Service Workers
* Rebooting the app
Of course all settings are lost and reverted to defaults.
The **checkbox** is intended for Service Worker mode only (it will complain if set in JQuery mode). It bypasses the appCache by:
* Clearing the Cache API caches
* Preventing Service Worker from using the appCache, forcing it to fetch all app files
When …

Provide methods for resetting the app and bypassing appCache

---

www/js/app.js

Fixes #808 and #801. Basically a one-liner, but formatted as two for legibility 😊.
EDIT: It will be interesting to see what effect this has on the secure browser tests...

Default to SW mode when accessing app as PWA

---

www/js/app.js
www/js/lib/uiUtil.js
www/js/lib/xzdec_wrapper.js
www/js/lib/zstddec_wrapper.js

This may fix #820. It also contains a fix for #812 because that blocks the app completely when loading from file protocol if the iframe is inaccessible, and prevents us accessing the API panel or posting an explanatory message to the user.
I've only tested this in Edge accessing from the file system. This is as close a simulation as I can get to the errors shown in the Ubuntu touch log. The race condition was undoubtedly affecting the loading sequence on Ubuntu touch, because it failed to fall back to ASM only with one of the decompressors (ZSTD), which happened to be the one needed.
Of course something else may be blocking the Ubuntu touch app, but fixing these two issues should allow us to diagnose better, if there are other issues in the way of a solution.

Fix race condition while loading decompressors

---

ubuntu_touch/manifest.json

- Name of the app in title in capital letters
- Updated description (It might have been too short)
- Update name hook (it may break updates if the app was installed before, it needs to be checked)

Update manifest for UT

---

.github/workflows/publish-extension.yaml
scripts/rewrite_app_version_number.sh

This should fix #823.
* Corrects the regexp that decides which release tags to build and push to docker
* Adds logging in the form of "echo" statements that will be visible to us in the Workflow run log
@mossroy Kindly check the bash script statements carefully with your "Linux glasses" on! I'm not very familiar with it. If it can be simplified, happy to do so.
I will create a quick test script (copy of the rewrite script in the workflow) with some sample input to be sure the rewriting works, and will test in WSL on Windows.

Fix errors in publish extension workflow and add logging

---

CHANGELOG.md

Please check if the descriptions are accurate for the changes regarding the Ubuntu Touch app.
I include 3.3.1 under the 3.3 milestone, so if people check the closed milestones, they will see all the commits for 3.3.0 and 3.3.1. I think this makes more sense than creating a specific milestone for 3.3.1, given that it is a minor version.

Changelog for v3.3.1

---

www/js/app.js

Removed unused variable messageChannel, and a weird character in a comment

Fix 2 codefactor warnings and remove whitespaces at end of lines of app.js

---

www/js/app.js

Fixes #821
Added a message alert when the user shuffles without loading a ZIM file
- Calling the `goToRandomArticle` only when `selectedArchive !== null && selectedArchive.isReady()` is true. Oherwise, calling the `uiUtil.systemAlert` with an apt message
- Issue #821

Adding an alert if shuffled without loading a ZIM file

---

www/index.html

as of `v0.0.0`, webp-hero is now licensed under the mit license 🎉 
simply because mit license is more popular 🤷‍♂️

update: webp-hero license link to mit

---

.github/workflows/publish-extension.yaml

**Note**: This app's hosting has **already** been migrated to our new (k8s-based) hosting. We can discuss different ways to offer this feature but as of now, your app is not reloading automatically on image pushes.
Manually trigger a *restart* on Kiwix k8s after a successful image push.
Previous behavior was to let Docker Hub trigger a restart on (former) hosting via a webhook:
- we don't want to rely on Docker Hub anymore
- hosting platform changed

Trigger webapp restart

---

scripts/create_all_packages.sh
scripts/package_firefox_extension.sh

Changes the destination of nightly uploads to master.download.kiwix.org on port 30022
As this service doesn't offer a shell anymore, converted the folder creation
and file discovery steps to more verbose, SFTP-based scripts.

Fix nightly build uploads

---

www/js/lib/uiUtil.js

Handle Enter key in Bootstrap modal dialogs

---

www/index.html
www/js/app.js
www/js/lib/uiUtil.js

Fixes #404
This is just a refresh of the work of Jaifroid in branch https://github.com/kiwix/kiwix-js/tree/Check-for-external-links-and-warn

Open external links in new tabs, and warn the user

---

service-worker.js

Send requested byte range from SW, with correct headers

---

www/js/lib/zimfile.js

Simple proposed fix for #875. This PR does the following:
* Increases the maximum supported dirEntry size to ~~4096 bytes~~ EDIT: now 5120 bytes
* Allows setting the size via a constant MAX_SUPPORTED_DIRENTRY_SIZE at the head of the file, thus making devs aware of the issue
* Provides a console warning if the dirEntry.url is longer than MAX_SUPPORTED_DIRENTRY_SIZE (url will be truncated, and no title will be found)
* Does not enter an infinite loop if dirEntry.url is longer than permitted size, but still returns the dirEntry.
The advantage of not throwing an error here, but instead printing a warning, is that often the dirEntry may be being accessed merely for search purposes, in which case no harm will come of returning a truncated dirEntry.url. However, a developer will be alerted to …

Explicitly set max supported dirEntry size

---

www/js/app.js

This is necessary for Firefox >=103, where the ServiceWorker API has been removed in WebExtensions.
See https://hg.mozilla.org/integration/autoland/rev/3a2907ad88e8
Fixes #877

Switch to PWA in Firefox extension when SW API is unavailable

---

www/js/app.js

Fixes display of unnecessary active content warning with mdWiki ZIMs. I think this more generally fixes #746, but not necessarily directly as a result of this PR... We first posted #746 because of new Type 1 Stackexchange ZIMs throwing the active content warning. But I just tested the master branch against `beer.stackexchange.com_en_all_2022-08.zim` (which I've verified is a Type 1 ZIM), and it doesn't throw any warnings. So perhaps those ZIM types no longer trigger the warning?

Exempt more content from active content warning

---

www/js/app.js
www/js/lib/zimArchive.js
www/js/lib/zimfile.js

Fixes #883. I have included some information for the user about how to open Zimit archive types. Clearly this would need to be kept up to date, but I think it's better to be helpful to users to avoid the kind of frustrating exchange you see in this [reddit comment](https://www.reddit.com/r/Kiwix/comments/wj8ivr/comment/ijwwyfs/?utm_source=share&utm_medium=web2x&context=3).

Detect Zimit archive type and warn user

---

www/index.html
www/js/app.js

New nautilus-based ZIMs don't trigger the active content warning in jQuery mode. This adds detection. There is also an incorrect instruction in the warning to "type a space". This doesn't do anything in Kiwix JS (in Kiwix JS Windows, typing a space opens a special Archive Index UI, and I think this instruction is a left-over from that).
We could make it so that typing a space displays the title index starting from the first entry within the current UI, but that would be a different PR.

Detect more ZIMs for active content warning

---

www/js/app.js

This is a very small correction to #889. The use of a + instead of a * prevented detection of simple scripts listed like `app.js` or `init.js` in some cases. This corrects that.

Fix issue preventing detection of some scripts in regexpActiveContent

---

.github/workflows/Release.yml
scripts/create_all_packages.sh

This was requested on https://github.com/kiwix/k8s/issues/50. It will provide the benefit that we will have permalinks to the latest nightly release, and is being implemented Kiwix-wide.
My Linux scripting skills are basic, but I think the included code should rename files like this:
```
build/kiwix-firefox-unsigned-extension-3.6commit-9a6e6f7.zip -->
build/kiwix-firefox-unsigned-extension_2022-10-06.zip
```
If you agree, I can test by dispatching the workflow on this branch.

Rename nightly packages to show date instead of revsion ID

---

CHANGELOG.md
manifest.json
service-worker.js
www/js/app.js

Proposed changelog for v3.6.0.
I have not included the fact that I had to disable end-to-end Unit tests temporarily while we look for a new solution, as it is not a "feature" of the released client.

Changelog for v3.6.0

---

www/js/app.js
www/js/lib/uiUtil.js

This is initial work on #916.
So far, it only deals with simple substitution of jQuery statements with their native DOM equivalents for hide and show selected by ID in `app.js`.

Replace jQuery for hide and show statements selected by ID

---

www/css/kiwixJS_mwInvert.css

Fixes #922. The added code exempts images with a class name beginning with `latex`. There are a number of `latex`-prefixed styles in the artofproblemsolving ZIMs such as `.latex` and `.latexcentered`, so we match any image style beginning with `latex` (`class^="latex"`).

Exempt more latex images from re-inversion in dark mode

---

www/js/app.js

I have tested the changes in Edge Chromium, Chrome, Firefox and IE 11.
So far everything has been working. Opening PR. Let me know if any changes are required :)
Fixes #919 .

Replace `.click()`, `.focus()` and `.attr()` jQuery functions with equivalent native JS

---

www/js/lib/zimArchive.js
www/js/lib/zimfile.js

Add fulltext directory listing to archive metadata

---

www/js/app.js
www/js/lib/uiUtil.js

Should potentially fix #920 
I have converted as many jQuery functions as I could to native JS.

Converts jQuery statements to native JS and regularize quotation marks

---

service-worker.js
www/css/app.css
www/index.html
www/js/lib/libzim-wasm.js
www/js/lib/uiUtil.js
www/js/lib/zimArchive.js
www/js/lib/zimfile.js

Fixes #929.
Currently there is no code to prevent initialization if the archive is split arbitrarily. I would prefer to be able to test what happens in this scenario.

Initialize the libzim worker

---

www/js/lib/zimArchive.js

Fixes #940.
It would be worth seeing if we can report interim results while waiting for dirEntry lookup promises to resolve.

Initiate full-text search earlier

---

.github/workflows/Release.yml

Fixes #914. This has the dry-run switch added for testing. Remove before merge.

Handle setting version number explicitly in release workflow

---

CHANGELOG.md
scripts/Publish-Implementation.ps1

Changelog for new release 3.7.0 (#943).

Changelog for version 3.7

---

.github/workflows/CI.yml
.github/workflows/Release.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish-extension.yaml

This was recommended to avoid warnings in the CI because old actions workflow rely on Node.js 12 which has been meanwhile deprecated

Use latest GitHub workflow actions

---

CONTRIBUTING.md
package.json

Added `http-server` script

---

service-worker.js
www/index.html
www/js/app.js

This addresses (but does not fix fully) #753 and #972. A full fix will require a separate PR implementing the Content Security Policy sandbox directive delivered via HTTP headers through the Service Worker.

Add sandbox to iframe

---

www/js/lib/zimArchive.js

This fixes the corruption of the `search.status` variable due to an illegal state transition `cancelled -> complete` in the full text search callback. Before it was causing the search results list to show around 10% of the time when I press enter quickly, and 100% if I cause the full text search to be delayed artificially. After this PR, the search results list cancellation bug for the full text search occurs 0% of the time.
Closes #977

Fix missing full text search cancellation

---

CHANGELOG.md
www/index.html
www/js/lib/uiUtil.js

Replaced use of jquery with native javascript calls while invoking and closing bootstrap modals. Although bootstrap 4.3 uses jquery under the hood, so complete removal is not possible until bootstrap is upgraded. 
closes #921

Removed usage of jquery while opening and closing bootstrap modals

---

www/js/app.js

Fixes #858 for jQuery mode. This does not touch ServiceWorker mode, as this should be handled natively in that mode. We cannot rely only on the filename extension, but must also consider the MIME type especially when there is no extension.

Fall back to MIME type when downloading doc in jQuery mode

---

www/css/app.css

This was accidentally removed along with the removal of jQuery. We can restore at least the opening animation with a CSS animation.

Restore modal animation for alert dialogue boxes

---

www/js/lib/uiUtil.js
www/js/lib/util.js

Fixes #841. The Promised dialogue boxes will be displayed sequentially. NB This doesn't use any `await`-like syntax, so we're not pseudo-pausing execution of the rest of the app. The alerts still have to be written asynchronously, it's just that only one will show at a time, and the dialogue boxes and resolving of associated Promises will be queued.

Add Promise queue to prevent overlapping dialogue boxes

---

tests/chromium.e2e.runner.js
tests/firefox.e2e.runner.js
tests/gutenberg_ro.e2e.spec.js
tests/ieMode.e2e.runner.js
tests/legacy-ray_charles.e2e.spec.js
tests/microsoftEdge.e2e.runner.js
tests/non-legacy.e2e.spec.js
tests/paths.js

closes #1042
Sorry I messed up my commit history in my last PR so I am reopening this after fixing the issue nonetheless

Tests for non legacy zim files 

---

package-lock.json
package.json
scripts/gitignore.patch
www/js/lib/translateUI.js

It turns out that we are not using any functions offered by i18next that cannot be used extremely simply by looking up the defined key in the language object. It therefore does not make sense to have the overhead of this (rather large) framework, until we actually need it.
This PR removes it, but leaves the (small amount) of code to interface with it commented out, with a comment explaining the steps needed to reactivate.

Temporarily remove i18next but leave instructions to reactivate

---

.github/workflows/CI.yml

Fixes #1088. This test got accidentally removed in a recent PR. Please see explanation in #1088 as to why I don't believe it's worth running Chrome (as opposed to Edge) tests specifically in the Windows VM. Testing is already quite slow, so we should focus on tests that clearly add value.

Restore IE Mode e2e testing in Windows

---

docker/dockerfile-browser-extension.pwa

Should partially fix #1099 for the GHCR container.

Ensure dockerfile serves jsonp with correct MIME type

---

www/js/app.js

Fix active content warning for PhET ZIMs

---

www/js/app.js
www/js/init.js

The only way discovered so far, short of writing an API, is to use a throw so that the bundle.js (or app.js) stops execution after the message is received from remote.

Completely exit local code on comms with remote

---

backgroundscript.js
manifest.fx.v3.json
rollup.config.js
scripts/create_all_packages.sh
scripts/package_firefox_extension.sh

This is for testing the MV3 extension in Firefox, as discussed in #1120.
To test, rename `manifest.json` to `manifest.cr.v3.json`, and then rename `manifest.fx.v3.json` to `manifest.json`. Then install a temporary Firefox extension in the usual way.
In sum: it works just like the old extension. It still requires using the remote PWA to run Service Workes as they are still completely disabled in Firefox MV3 extensions.

Switch to Manifest V3 for Firefox

---

i18n/en.jsonp.js
i18n/es.jsonp.js
i18n/fr.jsonp.js
www/js/app.js

Fixes #1122.
We could also display the article title being extracted using this method.

Launch spinner as soon as possible

---

www/js/app.js
www/js/init.js
www/js/lib/uiUtil.js

Transition animation cleanup and page animation turned off by default 

---

tests/unit/spec/tests.js
www/js/app.js
www/js/lib/zimArchive.js
www/js/lib/zimfile.js

This backports a facility in Kiwix JS PWA.

Add facility to extract and set ZIM metadata

---

www/js/lib/util.js
www/js/lib/zimArchive.js

This backports code from kiwix-js-pwa. It is possible to end up with extremely long-running searches that completely block the UI in some rare cases. This PR sets sensible maximum sizes for search looping.

Add sanity checks to prevent runaway searches

---

i18n/en.jsonp.js
i18n/es.jsonp.js
i18n/fr.jsonp.js
www/css/app.css
www/index.html
www/js/app.js
www/js/init.js

Closes #1139.
It's still a bit rough, but working in essence.

Slide away UI elements on scroll

---

tests/e2e/spec/gutenberg_ro.e2e.spec.js
www/css/app.css
www/index.html
www/js/app.js
www/js/lib/uiUtil.js

Enable tab access to file, folder and library selectors

---

i18n/en.jsonp.js
i18n/es.jsonp.js
i18n/fr.jsonp.js
www/index.html

This adds a tooltip for the library button explaining, amongst other things, that in a Chromium extension in ServiceWorkerLocal mode, only the basic library will load.

Translation corrections and add tool tip explaining library

---

backgroundscript.js

This attempts to make the browserAction generic, so that developers don't need to alter backgroundscript when testing manifest v2 and manifest v3 extensions.

Make a generic browserAction for backgroundscript

---

.github/workflows/CI.yml
tests/e2e/runners/chrome/chrome60.bs.runner.js
tests/e2e/runners/firefox/firefox70.bs.runner.js
tests/e2e/spec/gutenberg_ro.e2e.spec.js
tests/e2e/spec/legacy-ray_charles.e2e.spec.js

This disables Edge testing on Linux in GitHub, because we already test on Windows extensively in Edge, and there is a Chrome test in Linux which is the same thing.
It also fixes some of the descriptions of tests, and restricts the Firefox 70 test on BrowserStack to SW mode as stated in the test title.

Fix some anomalies in tests

---

tests/unit/index.html
www/js/lib/cache.js
www/js/lib/zimArchive.js

This provides better async support for loading archives.
It also provides a whenZimReady function in the loading chain that makes it easier to wait for the ZIM: this will be important for libzim loading (much slower to initialize).
Additionally adds a flag to the ZimArchive object `libzimReady`, which can be 'loading', 'ready' or 'error'.

Avoid side effects when loading archive

---

www/js/app.js

If the app is capable of ServiceWorker mode, but the user has switched to jQuery mode AND the Service Worker is unregistered (e.g. because the user has cleared data for the site), then the new code that initiates the Service Worker messaging causes a boot loop.
This PR fixes that by detecting the situation and showing a dialogue box warning the user that the app won't work offline in the current configuration, suggesting the user switch to ServiceWorker mode.

Fix anomalous boot loop when app is in jQuery mode and no SW is registered

---

www/js/app.js

In some cases, the online version was being opened due to wombat rewriting the location properties that need to be tested. So now we reconstruct them and ensure that ctrl/cmd clicking are handled by the Service Worker (except in jQuery mode, of course).

Fix opening of new Zimit tabs to local articles and PDFs

---

README.md
www/js/app.js

Fixes #1178 . This regression was due to the new Zimit code's passthrough mechanism for reactivating a clicked link. I forgot to turn the passthrough off, so it remained set even when a non-Zimit archive was loaded. Hence, PDFs were not handled properly in such archives if a Zimit archive had been opened in the same session.
The issue is that we must work around the fact that in Chromium browsers PDFs are (rightly IMHO) not trusted to be displayed in a sandbox, as they may have active content. So, in all browsers we open all PDFs in a new tab or window.

Fix failure to handle PDFs in openzim archive types

---

www/js/app.js
www/js/lib/abstractFilesystemAccess.js

resolves #1171
As the title says, replaced localStorage method with settingsStore method.
Heres a list of tests I performed:
- ran `npm run serve` and `npm run preview` and tested for chrome and firefox in both Jquery and serviceWorker modes.
- couldn't try the app in IE mode as I do not have a windows machine
- ran `npm test` all tests were successful
- tested the extension in developer mode on chrome
- tested the firefox extension
In all the tests, I was able to open the application and view .zim files. I also checked the localStorage and verified the presence of `kiwixjs-` prefix.

replaced localStorage with settingsStore method

---

www/js/lib/zimArchive.js

Warn instead of throwing if `minorVersion` > 2

---

www/js/lib/zimArchive.js

Fixes first bullet point of #1199.
It works like this:
1. Assume all archives are 'open' as a baseline
2. If we find warc-headers, it must be zimit classic, so change zimType to 'zimit'. This is true currently, but might not be true in the future - so if headers are re-introduced, the logic will need to be modified, perhaps by testing the location of Wombat in the ZIM, but that is considerably more complicated to do.
3. If we don't find warc-headers, check if there is Scraper metadata. If the archive is not detected as 'zimit', but was scraped by warc2zim, then it must be zimit2.

Add a way to detect that an archive is zimit2

---

www/js/app.js
www/js/lib/uiUtil.js

Although mostly static archives work well in Chromium extensions in ServiceWorkerLocal mode, highly dynamic ZIMs that contain inline JS (a poor coding practice, but highly prevalent) will have non-functional elements. This is because inline JS is banned in Chromium extensions, even in MV3.
But we have a workaround, which is to reload the app as a PWA from browser-extension.kiwix.org. We should therefore warn users opening zimit2 archives.
This PR modifies the JQuery "active content warning", so that it also shows on zimit2 landing pages when a user is in ServiceWorkerLocal mode.

Add content warning for zimit2 in service worker local mode

---

www/js/app.js
www/js/lib/abstractFilesystemAccess.js

There are a few issues with the code that enumerates archives in a directory:
* The first is that the code stores ALL files in the directory in the zimFilenames key. This PR adds a filter so only files matching the pattern `.zim\w?\w?$` (case insensitive) will be stored;
* The second is that the code was unnecessarily calling await functions several times to get values that could simply be stored in a variable;
* The third is that to test for a previously selected archive, a regex was being made from filenames without filtering for regex meta-charecters, which could easily lead to errors. In fact that's not necessary, as we can simply use `indexOf` without needing to do a regex test on the whole filename;
* The fourth is a longstanding bug where permissions appeared not be being retrieved …

Fix errors enumerating ZIM archives in directory

---

README.md
i18n/en.jsonp.js
i18n/es.jsonp.js
i18n/fr.jsonp.js
www/index.html
www/js/app.js
www/js/init.js
www/js/lib/abstractFilesystemAccess.js

In browsers that support the File System Access API (only Chromium browsers currently), it is now possible to re-open the last selected archive automatically if the user has given permanent access permissions.
This is a great step towards giving the app native-level UX.
However, there are situations where this could be annoying, so we need to provide a UI option to disable auto-loading.
Nota bene: this does not re-open the last read article like in Kiwix PWA, as that would require more code and more UI to avoid privacy concerns. It might be added in the future.
Fixes #1218.

Reopen last selected archive with File System Access API

---

www/js/app.js

Fixes #1222.
Will only be fixed for end users once we have a new extension release because the code runs in the local extension, not the remote.

Do not display File Selectors before jumping to remote

---

www/js/app.js

resolve #1157
Updated the regex to also match `ractive.js`. I was able to view the active content warning when PhET zims were opened in Safe mode.

update regex to match PhET

---

README.md

A better intro to the project in README.md

Rewrite README intro

---

www/css/app.css
www/js/app.js

For issue #1037 
Tests done:
`npm run serve`
`npm run preview`
`npm run build`, followed by` npm run serve` and using the localhost:xxxx/dist/? page. (should be same as running the extension)
Tested on both firefox and chromium.
Tested with both mdn web docs (which uses workers) and a smaller page that doesn't use workers. Tested in both jQuery and workers mode. Passed `npm test`. 
Ran `e2e-test` for firefox, just one error as seen below:
```
1) Gutenberg_ro test [ZSTD compression] [SW mode]
Sorting books by name:
AssertionError [ERR_ASSERTION]: 'Poezii' == 'Creierul, O Enigma Descifrata'
+ expected - actual
-Poezii
+Creierul, O Enigma Descifrata
```
On e2e-test for chromium, also just one error, as seen below:
```
1) Gutenberg_ro test [ZSTD compression] [SW mode]
Change Language: …
```

Non-file Dragging Bug Fix

---

www/js/lib/uiUtil.js

Fixes #1258.
As can be seen, this is a minor fix. Although we decode the entire URL, this should be an improvement in 95% of cases where the main URL does not contain encoded characters.
The main area of worry is PDFs, which is a common use case, so that functionality needs thorough testing with this workaround.

Decode overencoded external Zimit2 URLs

---

www/js/app.js

Fixes #1254.
This should be the last of the issue-fixing PRs prior to preparing release of v4.1.
It ensures that a ZIM file is not actually opened if the user selected a directory of archives using the File System Access `window.showDirectoryPicker()` method, and if that folder contains more than one archive. Without this fix, the first archive in the directory is inadvertently opened, which is unexpected and potentially insecure behaviour.
I need to test whether the same applies to the `webkitdirectory` method used by Firefox and Edge Legacy.

Do not jump to first file when using FSA API

---

_locales/en/messages.json
_locales/es/messages.json
_locales/fr/messages.json
manifest.json
rollup.config.js
scripts/create_all_packages.sh
scripts/package_chrome_extension.sh
scripts/package_firefox_extension.sh

Fixes #1118. According to the messages I receive when uploading an extension to the Edge or Chrome Stores, in order to internationalize the Store entry it is necessary to internationalize the manifests, adding those languages supported by the app. I've followed https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization, but I don't know for sure that this will do the trick until I attempt to upload the generated extension ZIPs.
We don't use the Chrome i18n module for i18n within the app, as we use a much simpler string-substitution system, and I'm not going to change that any time soon, especially as i18n for this app needs to work in multiple contexts, not just extensions.

Add i189 for Chromium store entries

---

www/js/lib/popovers.js

This PR Fixes #1276 
Hello Everyone!
In this PR i have fixed the popover inappropriate description extraction by adding regex logic so that only Required information will be shown. 
**NOTE**: This PR fixes almost every popover however there are still 3 - 5 popover's that i haven't able to fix for example calsacaus in Europe , Greenland and other 3 from USA. 
I have done all the necessary test 
1. Checked in both "**Restricted**" and "**ServiceWorker**" Everything is working fine check the ss below.
2. Unit tests `npm test` no issue 
3. End-to-end (e2e) `tests-e2e-iemode`-> There was some e2e.runner.js error which i have commented on this PR's Issue thread. I tried alternative http-server there wasn't any issue.
5. extension versions with production code tested
6. Browser Test -> Microsoft …

Fixed Brief Description Popover extraction Issue

---

www/js/app.js

Some rogue code copied from the PWA included an incorrect function call to hide the spinner. This PR corrects the calls to use the function provided in KJS (in uiUtil.js).

Change incorrect function calls to spinner

---

www/js/lib/popovers.js

This PR ports code from Kiwix PWA which supports the new behaviour of the CSS `zoom` property in Chrome >= 128 and Chromium-based browsers. We still have to test for the old behaviour, and exempt Safari and old MS browsers. See https://caniuse.com/css-zoom and https://github.com/kiwix/kiwix-js-pwa/issues/672 for more details.
This also ports some style improvements in dark mode.

Improve popover placement and style support

---

www/js/app.js

When searching for articles, it may sometimes happen that the article list (with search results) contains HTML (e.g., italics). In that case, if a user happens to click on an italicized word, then the dirEntry ID of the search list item won't be found.
This PR handles that situation, and searches for the nearest parent with a `className` matching `list-group-item`, before attempting to extract the dirEntry ID.

Handle user clicking on child element of list item

---

babel.config.js
rollup.config.js

Fixes #1337. This works by ensuring Babel always builds compacted code.

Build compact code by default

---

www/css/app.css
www/index.html
www/js/app.js
www/js/lib/uiUtil.js

fix #1212 
- Implemented a fully functional TOC drop-up, inspired by Kiwix-PWA and PR #1241
- When user clicks on drop-up button, TOC List is set up and displayed as drop-up menu.
- It is closed when drop-up button loses focus or when a section is clicked.
- Clicking a section scrolls the view to that section.

feat: added toc dropup like in Kiwix-PWA
