kiwix/kiwix-js

- service-worker.js
- www/js/app.js
- www/js/lib/archive.js
- www/js/lib/zimArchive.js
Support for reading binary files and some cleanup regarding the move
from manual callbacks to promises.
> Reading binary files.

- tests/tests.js
- www/js/app.js
- www/js/lib/zimArchive.js
- www/js/lib/zimDirEntry.js
The namespace has to be taken into account when titles are compared.
> Fix for finding some files in ZIM.

- service-worker.js
- tests/tests.js
- www/index.html
- www/js/app.js
- www/js/lib/util.js
- www/js/lib/zimArchive.js
I had to disable javascript & css again in the serviceworker, because the content received by the page still does not seem right.
I'm looking into it : the issue might be in the serviceworker, and not in the backend
> Jquery fallback

- tests/tests.js
- www/js/lib/util.js
- www/js/lib/zimArchive.js
Fixes #124.
On the other hands, it really slows down the title search.
When there are not many results, it launches 3 case insensitive searches before giving the result, which takes a few seconds.
> On title search, try some upper/lower case variants.

- www/js/lib/util.js
- www/js/lib/zimfile.js
Fixes #156
The performance can probably be optimized.
But, based on https://jsperf.com/multiplication-int-vs-bit-shifting-left , it might not be that bad (depending on the javascript implementation).
> Fix integer computation on ZIM backend to make it work on big ZIM files.

- www/index.html
- www/js/app.js
- www/js/lib/zimArchive.js
Oups, I also took in this PR the commit that fixes the redirection issues...
> Warn the user that the Service Worker mode is unstable for now

- service-worker.js
This is required by a modification of the ServiceWorker spec, that is
being enforced by recent browsers.
Cf https://bugzilla.mozilla.org/show_bug.cgi?id=1181127 for Firefox
Fixes #189
> Add the event listeners in the initial eval of the ServiceWorker script.

- www/js/app.js
> First fixes for stackexchange

- tests/tests.js
- www/js/app.js
- www/js/lib/abstractBackend.js
- www/js/lib/archive.js
- www/js/lib/zimArchive.js
Instead of a blank page. Fixes #126 
It does not apply to Evopedia archives
> Display the main page of the archive in the Home section.

- www/index.html
> Filter the file extensions the user can select in the input type file.

- service-worker.js
- tests/init.js
- tests/tests.js
- webextension/backgroundscript.js
- www/css/app.css
- www/index.html
- www/js/app.js
- www/js/init.js
- www/js/lib/abstractBackend.js
- www/js/lib/archive.js
- www/js/lib/normalize_string.js
- www/js/lib/osabstraction.js
- www/js/lib/title.js
- www/js/lib/titleIterators.js
- www/js/lib/uiUtil.js
- www/js/lib/utf8.js
- www/js/lib/util.js
- www/js/lib/webworker_bzip2.js
- www/js/lib/xzdec_wrapper.js
- www/js/lib/zimArchive.js
- www/js/lib/zimDirEntry.js
- www/js/lib/zimfile.js
> Replace "Evopedia" strings by "Kiwix" in all file headers.

- www/index.html
To avoid users from being frustrated by incompatible ZIM files like in #220
Fixes #221
> Add user info on which ZIM files are compatible.

- www/index.html
It might be worth rethinking the introduction and instructions as we use quite
technical terms and concepts.
> I've had a go at trying to improve the introductory guidance. 

- README.md
> Add info in README about the injection modes.

- browser-tests/nightwatch_runner.js
To try to solve Travis failures. See #228
> Add a waitForElementVisible for the expected article in UI tests

- browser-tests/nightwatch_runner.js
To try to solve Travis failures. See #228
> add and adjust waitForElementVisible calls in nightwatch.

- .travis.yml
> Fix .travis.yml to generate packages for both nightly and tags.

- www/index.html
Add .zimb-series extensions to <input ...> tag in .html
Hopefully I've got the hang of one-by-one PRs now -- thanks for the tutorial, very helpful!
> Add .zimb-extensions: fixes #254

- tests/tests.js
Now it gives an error in the console log.
Fixes #234
Also replace this.* by xhr.* to be consistent in the code style
> Give more info when a ZIM file is not found in unit tests.

- www/css/bootstrap-theme.css
- www/css/bootstrap.css
- www/js/lib/bootstrap.js
Implements kiwix-js #269 (Update bootstrap to 3.3.7). @Mossroy, please test. I have kept the old files (renumbered to xxxxx-3.3.4) and will delete once testing is completed satisfactorily.
> Update bootstrap to 3.3.7 #269

- www/js/app.js
Implements #272, elaborating on idea of @sharun-s (hiding of img.src in img.data-src).
This also hides the whitespace until the image is displayed.
> Implements #272 (Prevent unnecessary display of 404s)

- CHANGELOG.md
> Add a changelog file in the source code.

- README.md
> Add explicit statement about browser compatibility in README.

- www/js/lib/require.js
Tested and working on Firefox, Edge, Internet Explorer and Edge Mobile. Implements #270 .
> Update requireJS to 2.3.3

- .travis.yml
- scripts/create_all_packages.sh
- scripts/package_chrome_extension.sh
- scripts/package_firefox_extension.sh
- scripts/package_firefoxos_app.sh
- scripts/package_ubuntu_touch_app.sh
- scripts/push_to_gh_pages.sh
- scripts/setup_travis_env.sh
- ubuntu_touch/kiwix.apparmor
- ubuntu_touch/kiwix.desktop
- ubuntu_touch/manifest.json
And add double-quotes around path variables in all scripts to avoid issues with spaces in directory names
> Add ubuntu touch click packaging

- service-worker.js
- tests/tests.js
- www/dummyArticle.html
- www/index.html
- www/js/app.js
- www/js/lib/zimArchive.js
Please do not merge for now.
I create the PR to have some space to discuss.
I've implemented the idea of the "base" tag, that should fix #205 
But it's still quick and dirty
> Support subdirectories in articles

- scripts/create_all_packages.sh
So that they can be signed again by Mozilla. Fixes #314
> Fix the version string for nightly builds of Firefox extensions.

- www/index.html
Could you let me know if you're happy to approve a merge on this one?
> Fixes toolbar alignment #311

- www/js/app.js
Regression introduced by #310
Fixes #318
> Fix anchor links, that were broken because of the base tag

- CHANGELOG.md
- README.md
- www/index.html
- www/js/lib/abstractFilesystemAccess.js
- www/js/lib/zimArchive.js
In order to prepare a v2.2 release.
> Update README, About section and CHANGELOG.

- CHANGELOG.md
- scripts/create_all_packages.sh
> Fix package creation for a tag, and release date in changelog.

- www/js/app.js
- www/js/lib/uiUtil.js
This is the PR of the code already discussed. We should do a bit more testing on a variety of ZIMs, and when we're satisfied no further changes are required, I'll do a squash.
> Backport css cache

- service-worker.js
- tests/tests.js
- www/js/app.js
- www/js/lib/uiUtil.js
The anchor has to be removed before passing to the ZIM backend
Fixes #344
> Accept links to articles that have an anchor.

- .travis.yml
> Remove the jwt addon from travis configuration.

- www/js/app.js
> Avoid white page before displaying article content.

- www/js/app.js
> Fix 404 errors in http mode

- www/js/lib/xzdec_wrapper.js
- www/js/lib/zimfile.js
> Prevent xzdec_wrapper from decompressing several chunks at a time.

- www/js/app.js
By keeping it alive periodically.
> Workaround serviceworker state loss after a while

- CHANGELOG.md
- README.md
- www/index.html
- www/js/app.js
> Update README, CHANGELOG, and reword warnings on ServiceWorker mode.

- www/js/app.js
This PR addresses #428 . I think it will need quite wide testing. I've tested on pages such as `$1,000_Reward.html` which has a footnote href encoded as `%241%2C000_Reward.html#cite_note-TH-1`, as well as pages with parentheses in the URL, in Edge, but it needs wider testing before merging, on both the full English Wikipedia and other ZIMs (especially ZIMs with subdirectories, which I haven't tested yet).
> Support local anchors with URL

- service-worker.js
See #152 : it implements this issue, but only in ServiceWorker mode.
> Enable javascript injection in ServiceWorker mode

- service-worker.js
- www/js/app.js
And sometimes replace them by comments in the code.
Fixes #436
> Remove all debug logs in ServiceWorker mode

- README.md
- manifest.json
- scripts/create_all_packages.sh
- service-worker.js
- www/index.html
- www/js/app.js
- www/js/lib/zimDirEntry.js
- www/js/lib/zimfile.js
> Switch Kiwix and OpenZIM URLs to https, and fix invalid OpenZIM ones

- service-worker.js
This is a quick and dirty attempt.
It seems to fix #452 but is not ready to be merged yet.
It looks like the `'Accept-Ranges': 'bytes'` made it work.
Could you test it on Edge?
NB : it also seems to fix the subtitles issue
> Fix video seeking issue in SW mode on Chrome and Edge.

- www/index.html
- www/js/app.js
And update the wording of this mode in the "Settings" section
> Add explanations when the ServiceWorker mode does not work.

- CHANGELOG.md
Here is a proposal for the changelog (which will be copied in the stores of Firefox, Chrome and Ubuntu Touch)
> Update changelog for v2.5.0

- ubuntu_touch/kiwix.apparmor
- ubuntu_touch/manifest.json
Reference to this discussion : 
https://github.com/kiwix/kiwix-js/issues/375
> Upgrade to the Xenial (16.04) Ubuntu Touch platform

- .travis.yml
- README.md
- browser-tests/nightwatch_runner.js
- nightwatch.js
Following #324, new attempt to fix #323.
This is not ready to be merged yet.
The error message is now more meaningful than it was : 
After checking that element <#mwBA> has css property "float: right", it fails with : 
```
Error while running .moveTo() protocol action: unknown error: Element <iframe id="articleContent" class="articleIFrame" src="article.html" style="height: 551px;" cd_frame_id_="ec9c22917e519d9c1fac47d6df4e53e3"></iframe> is not clickable at point (920, 671). Other element would receive the click: <a class="btn btn-lg" id="btnTop" title="Top" href="#top">...</a> 
An error occurred while running .moveToElement() command on <#mwBTI>: unknown error: Element <iframe id="articleContent" class="articleIFrame" src="article.html" style="height: 551px;" …
```
> More complete scenario for ui tests

- service-worker.js
for epub, pdf and zip extensions.
Fixes #463.
> Add MIME-type in the SW response, for epub and other file extensions.

- www/js/app.js
This PR attempts to address #478. A single # in a hyperlink is defined as scroll to top of page. In jQuery mode, we need to recognize the # due to the base tag, and then we have to implement a scroll to top of the iframe window. 
The main use case for this that I'm aware of is the HTML5 version of Gutenberg books. They have a blue caret at the bottom of the page which should scroll to the top of the book. Therefore, this PR needs to be tested against, for example, `gutenberg_fr_all_2018-10.zim`. In jQuery mode, press a space in the search bar and open any book cover. Then go to the HTML5 version of the book, scroll down a little, and click the caret. The iframe window should scroll to the top.
@mossroy Can you think of any gotchas? I know `href="#"` is sometimes used with JavaScript, to …
> Handle single # in hyperlink

- tests/tests.js
- www/js/app.js
- www/js/lib/zimArchive.js
- www/js/lib/zimDirEntry.js
This addresses #485. Is this the right way to define the function? I've tested in Chromium and Edge in jQuery mode so far, and it seems to work.
> Provide getTitleOrUrl function to return url if title is empty

- README.md
> Change download URL of browser extension packages.

- www/js/app.js
- www/js/lib/uiUtil.js
This is proof of concept relating to #495 . It simplifies the parsing and programming of URLs in `parseAnchorsJQuery()`.
> Remove dependency on base URL

- www/js/app.js
This is a simple PR to address #520.
> Add further tests for existence of content

- tests.html
- www/js/app.js
These issues occur at least on Firefox>=68 and Chrome
Fixes #532
> Document and detect CORS issues with file:// protocol.

- .github/move.yml
This is needed to easy move a ticket from this repo to a repo in openzim organization.
> Move robot

- www/js/app.js
> Fix regex issues identified by Codefactor

- www/js/app.js
> Fix incorrect mimetype assignment

- www/js/app.js
> Simplify article loading in SW mode

- www/js/app.js
Let's see if this fixes #562 and #536.
> Prevent hiding of articleList on clicking searchArticles button

- www/css/app.css
Fix a few small problems reported by codefactor.io
> Css 0 values without unit

- .travis.yml
> Mask pkill returning 1

- www/js/app.js
- www/js/lib/uiUtil.js
Solved the issue of "Broken display when search results have special characters (#575)" on kiwix-js
>  Solved : Broken display when search results have special characters (#575)

- www/css/transition.css
- www/index.html
- www/js/app.js
- www/js/lib/uiUtil.js
Fixes #74
I have implemented a transition effect between different pages . This is just a naive version. Will require enhancements. Please checkout the transition effect and guide further......
> added transition between different pages (home/config/about) : Issue #74

- www/css/app.css
- www/js/lib/uiUtil.js
Fixes #591. Because this PR is essentially a missing piece of #582, I will merge it on Friday 7th if there are no observations raised.
> Fix missing footer and footer style with light contentTheme

- CHANGELOG.md
@mossroy sir, @Jaifroid sir please review
> minor changes in CHANGELOG.md

- www/css/app.css
- www/js/app.js
A vertical scrollbar was appearing along with the one in the iframe
component which was unnecessary. This PR removes it by changing a small attribute in _app.css_.
Fixes #566.
> Fixed extra vertical scrollbar appearing

- www/index.html
not sure what to do, maybe a latest url on the webserver for all files?
> ray charles zim has different url, which will change in 2 months again

- CHANGELOG.md
@mossroy Please note suggested new changelog format (proposed to use only for this and future releases) as suggested by @kelson42 in https://github.com/kiwix/kiwix-js-windows/issues/29 
Do you like this?
Milestone closed log is here:
https://github.com/kiwix/kiwix-js/milestone/21?closed=1 
but note a lot of issues there were closed without fixes.
> Update changelog for v2.7.0

- nightwatch.js
- service-worker.js
- www/js/app.js
Changed var declarations for constants to const
Improves readability as well as browser/app memory management.
> fixes #614 

- CHANGELOG.md
I found one more to put in, though it's not a real change...
> Update CHANGELOG for v3.0.0

- CHANGELOG.md
- manifest.json
- manifest.webapp
- scripts/create_all_packages.sh
- ubuntu_touch/manifest.json
- www/index.html
@mossroy Please do a quick check that this is OK.
> Prepare source code for 3.1

- CHANGELOG.md
This is the suggested CHANGELOG for the proposed version 3.1 (see #681).
> Changelog for v3.1

- .github/workflows/nightly_or_release.yml
- scripts/package_chrome_extension.sh
- scripts/package_firefox_extension.sh
- scripts/package_ubuntu_touch_app.sh
This PR is to make corrections as a result of testing of #685.
> Corrections to nightly_or_release GitHub Action

- .github/workflows/CI.yml
- CHANGELOG.md
- manifest.json
- manifest.webapp
- scripts/create_all_packages.sh
- ubuntu_touch/manifest.json
- www/index.html
> Prepare source code for 3.2

- scripts/create_all_packages.sh
Should fix #691, but untested so far because on my local machine the files are already rw-r-r in wsl, so must be tested on real linux?
> Action: changemod before upload

- README.md
- package.json
- tests/karma.conf.local.js
Follows-up https://github.com/kiwix/kiwix-js/pull/672.
> Document npm dependency for unit tests

- README.md
The previous one does not work any more
> Update URL for Ubuntu Touch app

- www/index.html
- www/js/app.js
- www/js/lib/settingsStore.js
Issue: #704 
The changes are made in www/js/app.js
It does the intended action of focusing search form and scrolling to top on 'home' keydown.
> "Home" keyboard key now focuses search form.

- CHANGELOG.md
> v3.1.0 milestone URL added in CHANGELOG.md

- package-lock.json
- package.json
This is to test whether we can upate Karma to 6.3.4 to eliminate vulnerabilities.
> Update Karma to 6.3.4

- manifest.json
> Add a CSP to allow WASM in Chromium extensions

- www/index.html
> Document workaround for image download

- www/css/app.css
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>
Fixes: #776
Before:
After:
> Corrected the form height in `Display Settings`.

- www/css/app.css
> Aligned search-bar with the search-button.

- www/index.html
Fixes: #775
This PR adds tooltips to icons and settings and all the changes are associated with `www/index.html` file.
> Added tooltips to icons and settings.

- www/js/app.js
- www/js/lib/uiUtil.js
> Deal correctly with favicon

- www/js/app.js
> Fix warning on each start when ServiceWorker is not supported

- CHANGELOG.md
This is still work in progress.
> Update changelog for v3.3.0

- www/js/app.js
- www/js/lib/settingsStore.js
- www/js/lib/zimArchive.js
- www/js/lib/zimArchiveLoader.js
Removing the dependency of a backend js file on the UI.
Removed the dependency of `zimArchive.js` on `uiUtil.js` as the first part of this PR
- Unable to reproduce the error message
- Please test it and let me know how I can do the same
- Issue #813
> Remove-the-dependencies-on-the-UI-of-JS-backend-files-#813

- CHANGELOG.md
I've attempted to describe the changes since 3.3.1, but some are quite tricky to describe and the wording may need to be tweaked for accuracy.
> Changelog for version 3.4.0

- www/index.html
- www/js/app.js
- www/js/lib/uiUtil.js
Fixes #942 and also ensures the API panel is updated in a timely manner.
> Update documentation of full text search

- scripts/create_all_packages.sh
> Remove hard coding of WIP in build script

- scripts/create_all_packages.sh
Fixes #915. I've also added a switch to simulate a CRON_LAUNCHED job. The script is now more verbose, explaining what it's doing and instructing the developer on location of unsigned packages.
> Publish some installation packages to release

- scripts/create_all_packages.sh
> Remove dev versions of libzim binaries in packaging script

- manifest.json
- manifest.webapp
- service-worker.js
- ubuntu_touch/manifest.json
- www/js/app.js
Closes #955 using the new proposed schema instead of the -WIP suffix.
> Prepare source code for 3.7.1

- README.md
In particular, this updates the Limitations section to reflect new capabilities.
> Update readme to reflect new capabilities

- www/js/app.js
> Check for PWA update after startup

- www/index.html
- www/js/app.js
> Add option to disable drag-and-drop

- CHANGELOG.md
Towards v3.8.0 release. See #979.
> CHANGELOG for v3.8.0

- www/index.html
- www/js/app.js
> Add PWA ServiceWorker mode for Chromium extension

- www/js/app.js
> Add a warning colour when appCache is disabled

- .eslintrc.cjs
- www/js/app.js
In response to #1014, we need to fix at least blocking ESLint issues.
> Fix blocking ESLint issues

- .eslintrc.cjs
- nightwatch.js
- tests/init.js
- tests/karma.conf.local.js
- tests/karma.conf.saucelabs.js
- tests/tests.js
- www/js/app.js
- www/js/lib/abstractFilesystemAccess.js
- www/js/lib/filecache.js
- www/js/lib/settingsStore.js
- www/js/lib/utf8.js
- www/js/lib/util.js
- www/js/lib/xzdec_wrapper.js
- www/js/lib/zimArchive.js
- www/js/lib/zimArchiveLoader.js
- www/js/lib/zimDirEntry.js
- www/js/lib/zimfile.js
- www/js/lib/zstddec_wrapper.js
> Fix issues identified by ESLint

- www/index.html
> Update in-app documentation

- .github/workflows/publish-extension.yaml
- CONTRIBUTING.md
- README.md
- _config.yml
- scripts/gitignore.patch
> Mop up some issues with bundling system

- .github/workflows/CI.yml
- tests/ieMode.e2e.runner.js
- tests/kiwix-js.e2e.spec.js
> Add more explicit tests for ServiceWorker compatibility

- CONTRIBUTING.md
- TESTS.md
- tests/chromium.e2e.runner.js
- tests/firefox.e2e.runner.js
- tests/ieMode.e2e.runner.js
- tests/legacy-ray_charles.e2e.spec.js
- tests/microsoftEdge.e2e.runner.js
- www/index.html
Closes #1045. This should provide enough information for #1042.
> Add documentation and licensing for e2e tests

- .github/workflows/CI.yml
> Exempt BrowserStack tests for PRs from forked Repos

- CONTRIBUTING.md
- TESTS.md
> Update documentation on tests for BrowserStack

- .github/workflows/CI.yml
> Attempt to force failure if one test fails with PowerShell in GitHub Actions

- tests/legacy-ray_charles.e2e.spec.js
Fixing issues identified in #1057.
> Fix legacy test for IE mode

- .github/workflows/CI.yml
- tests/gutenberg_ro.e2e.spec.js
- tests/legacy-ray_charles.e2e.spec.js
- tests/paths.js
trying to fix #1069
I am creating this PR to fix the CI issue. It might take multiple attempts so please bear with me
> Trying to CI timeout issue

- .github/workflows/CI.yml
- scripts/Publish-Implementation.ps1
- scripts/Set-AppVersion.ps1
- scripts/create_all_packages.sh
- scripts/rewrite_app_version_number.sh
> Update build scripts to use version from init.js

- .github/workflows/CI.yml
- ADDING_DEPENDENCIES_NODE_MODULES.md
- scripts/gitignore.patch
A corrupt version slipped into a PR.
> Fix corrupt gitignore patch

- www/index.html
> Fix file picking in latest Chromium browsers for Android

- docker/dockerfile-browser-extension.pwa
> Add missing i18n folder to dockerfile

- scripts/create_all_packages.sh
- scripts/package_chrome_extension.sh
- scripts/package_firefox_extension.sh
- scripts/package_firefoxos_app.sh
Fixes #1114. The internationalization files were missing from some of the packaged builds.
> Ensure packages contain i18n files

- package-lock.json
Seeing if tests work when pushed by maintainer.
> Update babel-core and fix vulnerabilities

- www/css/app.css
- www/index.html
> Fix some UI spacing issues

- CHANGELOG.md
- www/js/app.js
> Fix scrolling of search results

- .github/workflows/CI.yml
- tests/e2e/runners/chrome/chrome58.bs.runner.js
- tests/e2e/runners/chrome/chrome60.bs.runner.js
- tests/e2e/runners/chrome/chromium.e2e.runner.js
- tests/e2e/runners/edge/ieMode.e2e.runner.js
- tests/e2e/runners/edge/microsoftEdge.e2e.runner.js
- tests/e2e/runners/firefox/firefox.e2e.runner.js
- tests/e2e/runners/firefox/firefox56.bs.runner.js
- tests/e2e/runners/firefox/firefox70.bs.runner.js
- tests/e2e/runners/safari/safari14.bs.runner.js
- tests/e2e/spec/gutenberg_ro.e2e.spec.js
- tests/e2e/spec/legacy-ray_charles.e2e.spec.js
- www/js/lib/zimfile.js
> Fix zim file.name property when remote testing and improve test formatting

- .github/workflows/CI.yml
- i18n/en.jsonp.js
- i18n/es.jsonp.js
- i18n/fr.jsonp.js
- service-worker.js
- tests/e2e/runners/chrome/chrome60.bs.runner.js
- tests/e2e/runners/edge/ieMode.e2e.runner.js
- tests/e2e/runners/firefox/firefox70.bs.runner.js
- tests/e2e/spec/gutenberg_ro.e2e.spec.js
- tests/e2e/spec/legacy-ray_charles.e2e.spec.js
- www/js/app.js
- www/js/lib/abstractFilesystemAccess.js
> Remove unnecessary initOrKeepAliveServiceWorker

- docker/dockerfile-browser-extension.pwa
- rollup.config.js
- service-worker.js
- www/js/lib/zimArchiveLoader.js
File not included in dist build, and also wrong manifest was included in the dockerfile...
> Fix missing webmanifest

- www/js/app.js
- www/js/lib/uiUtil.js
- www/js/lib/zimArchive.js
Fixes #1183 and second bullet point of #1199.
> Open external links and PDFs outsde zimit sandbox

- www/index.html
- www/js/app.js
- www/js/lib/uiUtil.js
> Deal with zimit2 URL handling in jQuery mode

- .github/workflows/CI.yml
- .github/workflows/Release.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-extension.yaml
> Fix deprecated actions/checkout

- CHANGELOG.md
- README.md
Suggested wording for v4.0 CHANGELOG:
> CHANGELOG for v4.0

- README.md
Update the firefox add-ons download link from the French version to the English
> Update the firefox add-ons download link

- www/js/app.js
Fixes #1255. Sorry, should be last one. Again, its very simple, but I forgot I said I'd observed this again while testing popover code and it does need fixing.
> Extend time between reloads for failed SW registration

- package-lock.json
- www/css/app.css
Fixes #1288 
##What this PR does?
This PR sets the select random button size equal to that of search button size on mobile/tablet screens.
> Fixed the size of select random button on home page same as search button_#1288

- www/css/app.css
This PR Fixes the page dark mode theme issue created by PR #1329 
Read this chat for more info [Link](https://github.com/kiwix/kiwix-js/pull/1329#issuecomment-2817027914)
SS For Reference
**Before** 
**After**
> Fixed the folder dark mode style

- .github/workflows/Release.yml
> Update GH release action to Ubuntu 22.04
